<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit19bbbf90c26fde2d18ddb169baa32908
{
    public static $prefixLengthsPsr4 = array (
        'P' =>
        array (
            'Psr\\Http\\Server\\' => 16,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\EventDispatcher\\' => 20,
            'Psr\\Clock\\' => 10,
        ),
        'L' =>
        array (
            'League\\Uri\\' => 11,
            'League\\OAuth2\\Server\\' => 21,
            'League\\Event\\' => 13,
            'Lcobucci\\JWT\\' => 13,
        ),
        'D' =>
        array (
            'Defuse\\Crypto\\' => 14,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Http\\Server\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-server-middleware/src',
            1 => __DIR__ . '/..' . '/psr/http-server-handler/src',
        ),
        'Psr\\Http\\Message\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\EventDispatcher\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/event-dispatcher/src',
        ),
        'Psr\\Clock\\' =>
        array (
            0 => __DIR__ . '/..' . '/psr/clock/src',
        ),
        'League\\Uri\\' =>
        array (
            0 => __DIR__ . '/..' . '/league/uri',
            1 => __DIR__ . '/..' . '/league/uri-interfaces',
        ),
        'League\\OAuth2\\Server\\' =>
        array (
            0 => __DIR__ . '/..' . '/league/oauth2-server/src',
        ),
        'League\\Event\\' =>
        array (
            0 => __DIR__ . '/..' . '/league/event/src',
        ),
        'Lcobucci\\JWT\\' =>
        array (
            0 => __DIR__ . '/..' . '/lcobucci/jwt/src',
        ),
        'Defuse\\Crypto\\' =>
        array (
            0 => __DIR__ . '/..' . '/defuse/php-encryption/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit19bbbf90c26fde2d18ddb169baa32908::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit19bbbf90c26fde2d18ddb169baa32908::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit19bbbf90c26fde2d18ddb169baa32908::$classMap;

        }, null, ClassLoader::class);
    }
}
